In [1]:
#Álgebra Linear com numpy
import numpy as np

In [44]:
#Multiplicar duas matrizes
A = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
B = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(" Dimensão de A:", A.shape) #2 linhas, 4 colunas
print(A)
print(" Dimensão de B:", B.shape) #2 linhas, 4 colunas
print(B)

 Dimensão de A: (2, 4)
[[1 2 3 4]
 [5 6 7 8]]
 Dimensão de B: (4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
#Número de colunas de A = ao número de linhas de B (4). Podemos multiplicar
C = np.dot(A, B)
print(" Dimensão de C:", C.shape) #2 linhas, 3 colunas
print(C)

 Dimensão de C: (2, 3)
[[ 70  80  90]
 [158 184 210]]


In [46]:
#Matriz transposta
D = C.T
print(" Dimensão de D:", D.shape) #3 linhas, 2 colunas
print(D)

 Dimensão de D: (3, 2)
[[ 70 158]
 [ 80 184]
 [ 90 210]]


In [47]:
#Transposta do produto é igual ao produto das transpostas
print(np.dot(A,B).T) 
print("\n")
print(np.dot(B.T, A.T))

[[ 70 158]
 [ 80 184]
 [ 90 210]]


[[ 70 158]
 [ 80 184]
 [ 90 210]]


In [48]:
# Álgebra linear com tensorflow
import tensorflow as tf
print(tf.__version__)

2.0.0


In [49]:
a = tf.constant([1, 2, 3, 4, 5, 6, 7, 8], shape=[2, 4])
b = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], shape=[4, 3])
print(a)
print("\n")
print(b)

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


In [50]:
c = tf.tensordot(a, b, axes=1)
print(c)

tf.Tensor(
[[ 70  80  90]
 [158 184 210]], shape=(2, 3), dtype=int32)


In [51]:
d = tf.transpose(c)
print(d)

tf.Tensor(
[[ 70 158]
 [ 80 184]
 [ 90 210]], shape=(3, 2), dtype=int32)
